services:
  interview-trainer-service:
    image: yonatanmatuz/interview-trainer-production-image:latest
    build: .
    container_name: interview-trainer-container
    ports:
      - 443:3000
    restart: unless-stopped

    